Publish your whole static website to github,only use emacs org-mode(with git)
* Who need this? Why and How?
If your like write something, and don't want to be troubled by the format.
Maybe you will like the emacs org-mode, which use plain text to orginize your 
documents.
- emacs user
- no format wirte lover
- want to share or want to web look
** Why use github to hold your website(static)
Github can hold your static website, no storage limmitation, no format limitation, and for free.
** Why use org-mode to publish website.
When you have some org-mode files, if you want to share them with others, 
or you just want to see them in a web style(for wiki like style, for beautiful look,etc) 
** How to use github to hold your website
- Create a repository in github Follow this [[https://help.github.com/articles/user-organization-and-project-pages][office toturial]]
- Upload an index.html to github
#+BEGIN_SRC sh
$ echo "My GitHub Page" > index.html
$ git commit -a -m "First Pages commit"
$ git commit origin master
#+END_SRC
** How to pubish your website
*** Use org-mode to publish the html
Use this [[http://orgmode.org/worg/org-tutorials/org-publish-html-tutorial.html][official tutorial]] to learn how to publish Org-mode files to HTML.
*** Use git to commit website to github.io

* Customlize the css tempalte
** Basic: CSS layout
*** Normal css layout
- header(basically include logo, meaubar)
- Site content(include content and sidebar)
- footer
*** org css layout
- preamble
- content
- table of content
- postamble

** Find a free css template you like.
- edit the .eamcs file to replace the default preamble & postamble
#+BEGIN_SRC emacs-lisp
(require 'org-publish)
(setq org-publish-project-alist
      '(
        ("org-notes"
         :base-directory "~/space/org/"
         :base-extension "org"
         :publishing-directory "~/space/"
         :recursive t
         :publishing-function org-publish-org-to-html
         :headline-levels 4
         :section-numbers nil
         :auto-preamble t
         :auto-sitemap t                ; Generate sitemap.org automagically...
         :sitemap-filename "sitemap.org"  ; ... call it sitemap.org (it's the default)...
         :sitemap-title "Sitemap"         ; ... with title 'Sitemap'.
         :author "idlesong"
         :email "idele at gmail dot com"
         :style "<link rel=\"stylesheet\" type=\"text/css\" href=\"css/stylesheet.css\"/>"
         )

        ("org-static"
         :base-directory "~/space/org/"
         :base-extension "css\\|js\\|png\\|jpg\\|gif\\|pdf\\|mp3\\|ogg\\|swf"
         :publishing-directory "~/space/"
         :recursive t
         :publishing-function org-publish-attachment
         )
        ("org" :components ("org-notes" "org-static"))
        ;;
        )
)

(setq org-export-html-preamble "

    <div id=\"header\">
      <div id=\"logo\">
        <h1><img src=\"img/my_icon_mid.jpg\"  /> Idlesong's_<a href=\"#\">Mind Space</a></h1>
        <div class=\"slogan\">for colorful life</div>
      </div>
      <div id=\"menubar\">
        <ul id=\"menu\">
          <li class=\"current\"><a href=\"index.html\">Home</a></li>
          <li><a href=\"tech.html\">Tech</a></li>
          <li><a href=\"life.html\">Life</a></li>
          <li><a href=\"other.html\">Other</a></li>
          <li><a href=\"contact.html\">Contact Me</a></li>
        </ul>
      </div>
    </div>

")

(setq org-export-html-postamble "
    <p>Copyright @idlesong <a href=\"http://orgmode.org\">;design from HTML5webtemplates.co.uk </a> </p>
    ")
#+END_SRC
** replace the default css
* Reference
[[http://www.ruanyifeng.com/blog/2012/08/blogging_with_jekyll.html][阮一峰:搭建一个免费的,无限流量的Blog]]
